# 数据源
spring:
  datasource:
    ### 在同一个网络中，bridge  pro-net   容器之间不仅可以通过ip访问，而且可以通过名称
    # 直接连接mysql 容器
#    url: jdbc:mysql://my-mysql:3306/db_docker_springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#  连接haproxy 实现mysql高可用
    url: jdbc:mysql://192.168.136.200:3306/db_docker_springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis托管mapper文件
mybatis:
  mapper-locations: classpath:mapper/*.xml



